# Generated by Django 3.0.3 on 2020-07-07 09:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20200706_2030'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='intial_bid',
            new_name='initial_bid',
        ),
        migrations.AlterField(
            model_name='listing',
            name='author',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='listing_author', to=settings.AUTH_USER_MODEL),
        ),
    ]
