# Generated by Django 3.0.3 on 2020-07-11 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auto_20200711_0825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='listing',
            name='initial_bid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
