# Generated by Django 3.0.3 on 2020-07-11 13:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_auto_20200711_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='bids',
            field=models.ManyToManyField(through='auctions.Bid', to=settings.AUTH_USER_MODEL),
        ),
    ]
