# Generated by Django 3.0.3 on 2020-07-11 14:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_auto_20200711_1335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='wishlist',
        ),
        migrations.AddField(
            model_name='listing',
            name='watchlist',
            field=models.ManyToManyField(blank=True, related_name='watchlist_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
