# Generated by Django 3.0.7 on 2020-07-21 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_post_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='modified',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
