# Generated by Django 3.0.3 on 2020-07-31 11:25

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('computedart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('grid', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(4), django.core.validators.MaxValueValidator(200)])),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='listing_author', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
