# Generated by Django 3.0.3 on 2020-07-31 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computedart', '0002_configuration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='title',
            field=models.CharField(max_length=256),
        ),
    ]
