# Generated by Django 3.0.3 on 2020-08-02 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computedart', '0006_configuration_animate'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='image_file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
