# Generated by Django 3.0.3 on 2020-08-02 19:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computedart', '0008_auto_20200802_1847'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='circle_chance',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='configuration',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%d/'),
        ),
    ]
