# Generated by Django 3.0.3 on 2020-08-04 20:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computedart', '0010_configuration_color_chance'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='four_part_chance',
            field=models.PositiveSmallIntegerField(default=100, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
            preserve_default=False,
        ),
    ]
